//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniinfoAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_Chamado
    {
        public string descricao { get; set; }
        public System.DateTime dataChamado { get; set; }
        public string statusAtendimento { get; set; }
        public string nome { get; set; }
    }
}
