//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniinfoAsp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loginn
    {
        public int idLogin { get; set; }
        public int idFuncionario { get; set; }
        public string login { get; set; }
        [DataType(DataType.Password)]
        public string senha { get; set; }
        public int idNivelAcesso { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual nivelAcesso nivelAcesso { get; set; }
    }
}
