//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniinfo_Desk.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Con_Chamado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Con_Chamado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        private System.DateTime dataChamadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusAtendimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime dataChamado {
            get {
                return this.dataChamadoField;
            }
            set {
                if ((this.dataChamadoField.Equals(value) != true)) {
                    this.dataChamadoField = value;
                    this.RaisePropertyChanged("dataChamado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string statusAtendimento {
            get {
                return this.statusAtendimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.statusAtendimentoField, value) != true)) {
                    this.statusAtendimentoField = value;
                    this.RaisePropertyChanged("statusAtendimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento HelloWorldResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.HelloWorldResponse HelloWorld(Uniinfo_Desk.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> HelloWorldAsync(Uniinfo_Desk.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarChamadoResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse ConsultarChamado(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> ConsultarChamadoAsync(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Uniinfo_Desk.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Uniinfo_Desk.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamado", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody Body;
        
        public ConsultarChamadoRequest() {
        }
        
        public ConsultarChamadoRequest(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarChamadoRequestBody {
        
        public ConsultarChamadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarChamadoResponseBody Body;
        
        public ConsultarChamadoResponse() {
        }
        
        public ConsultarChamadoResponse(Uniinfo_Desk.ServiceReference.ConsultarChamadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarChamadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamadoResult;
        
        public ConsultarChamadoResponseBody() {
        }
        
        public ConsultarChamadoResponseBody(Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamadoResult) {
            this.ConsultarChamadoResult = ConsultarChamadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Uniinfo_Desk.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Uniinfo_Desk.ServiceReference.WebServiceSoap>, Uniinfo_Desk.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.HelloWorldResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.HelloWorld(Uniinfo_Desk.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Uniinfo_Desk.ServiceReference.HelloWorldRequest inValue = new Uniinfo_Desk.ServiceReference.HelloWorldRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.HelloWorldRequestBody();
            Uniinfo_Desk.ServiceReference.HelloWorldResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.HelloWorldAsync(Uniinfo_Desk.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Uniinfo_Desk.ServiceReference.HelloWorldRequest inValue = new Uniinfo_Desk.ServiceReference.HelloWorldRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.HelloWorldRequestBody();
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarChamado(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamado(request);
        }
        
        public Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamado() {
            Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody();
            Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarChamado(inValue);
            return retVal.Body.ConsultarChamadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarChamadoAsync(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> ConsultarChamadoAsync() {
            Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody();
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarChamadoAsync(inValue);
        }
    }
}
